### ISSUE TITLE
Upload to hackage?

### ISSUE THREAD

**Issue by pkamenarsky** [owainlewis/sengrid-hs#1]
I'd like to use this package in a project of mine, is there anything that speaks against uploading it to hackage?

**Comment by owainlewis** [comment]
Hi. No it would make sense to get it uploaded to hackage. Will look into doing this. Thanks .

**Comment by pkamenarsky** [comment]
Perfect, thanks!

**Comment by owainlewis** [comment]
Done. Please let me know if there are any problems with the relase. Thanks http://hackage.haskell.org/package/sendgrid-haskell
