### ISSUE TITLE
HTML FORMAT

### ISSUE THREAD

**Issue by MonrealRyan** [owainlewis/sengrid-hs#5]
hi is there a possible way to sent a HTML format using this library?

**Comment by owainlewis** [comment]
I think it's a missing feature. Easy enough to add in. Will try and take a look. Thanks

**Comment by owainlewis** [comment]
Added html example. Let me know if you have any more issues :+1:

**Comment by MonrealRyan** [comment]
hi thank you for the response. does it update the file on hackage?

**Comment by MonrealRyan** [comment]
also i think html must be an html data type just a suggestion.

**Comment by owainlewis** [comment]
Will push when I get some time (perhaps tomorrow). You should be able to pass in raw HTML strings to the API `"<h1>FOO</h1>"` etc.

**Comment by MonrealRyan** [comment]
Thank you :)

**Comment by MonrealRyan** [comment]
Requesting for the update on hackage. Thank you.
